events {}

http {
    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;

    server {
        listen 8080;
        server_name api.poc.local;

        # =========================================================
        # API traffic -> Istio
        #
        # /api/user/*
        # /api/login/*
        # /api/admin/*
        #
        # Istio performs service-level routing.
        # =========================================================

        location /api/ {
            proxy_pass http://host.docker.internal:80;

            proxy_set_header Host api.poc.local;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }


        # =========================================================
        # FRONTEND ALIASES
        #
        # These emulate URI rewriting that could be implemented
        # using a CloudFront Function.
        # =========================================================

        # /userdata -> S3 /user/
        location = /userdata {
            rewrite ^ /user/index.html last;
        }

        # /login -> S3 /login/
        location = /login {
            rewrite ^ /login/index.html last;
        }

        # /admin -> S3 bucket root
        location = /admin {
            rewrite ^ /index.html last;
        }


        # =========================================================
        # DEFAULT STATIC CONTENT -> S3
        #
        # Everything not under /api/ eventually arrives here.
        # =========================================================

        location / {
            proxy_pass http://host.docker.internal:4566/html/;

            proxy_set_header Host host.docker.internal;
        }
    }
}