apiVersion: constraints.gatekeeper.sh/v1beta1
kind: DevMaxReplicas
metadata:
  name: denyonreplicas
spec:
  match:
    namespaces:
      - test-deployments
    excludedNamespaces:
      - gatekeeper-system
      - kube-system
      - kyverno

    scope: Namespaced
    kinds:
      - apiGroups: [""]
        kinds:
          - Pod
      - apiGroups: ["apps"]
        kinds:
          - Deployment

  parameters:
    replicas: 1