events {}

http {
    access_log /var/log/nginx/access.log;

    server {
        listen 8080;
        server_name api.poc.local;

        #
        # /api -> Istio
        #
        location /api {
            proxy_pass http://host.docker.internal:80;

            # Required for the Istio Gateway/VirtualService host match
            proxy_set_header Host api.poc.local;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        #
        # /user -> Istio
        #
        location /user {
            proxy_pass http://host.docker.internal:80;

            proxy_set_header Host api.poc.local;

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        #
        # Everything else -> S3/Flocci
        #
        location / {
            proxy_pass http://host.docker.internal:4566/test-bucket/;
        }
    }
}