apiVersion: mutations.gatekeeper.sh/v1
kind: AssignMetadata
metadata:
  name: enableistio
spec:
  match:
    scope: Clustered
    excludedNamespaces:
      - kube-local
      - kube-system
      - kyverno
      - gatekeeper-system
    kinds:
      - apiGroups: [""]
        kinds: ["Namespace"]
  location: "metadata.labels.istio-injection"
  parameters:
    assign:
      value: "enabled"
      