---
apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8simagecheck
spec:
  crd:
    spec:
      names: 
        kind: K8sImageCheck
      validation:
        openAPIV3Schema:
          type: object
          properties:
            imageRepo:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8simagecheck

        violation[{"msg": msg}] {
          container := input.review.object.spec.template.spec.containers[_]

          not allowed_repo(container.image)

          msg := sprintf(
            "Container '%s' uses image '%s'. Images must come from '%s'",
            [
              container.name,
              container.image,
              input.parameters.imageRepo
            ]
          )
        }
        allowed_repo(image) {
        repo := input.parameters.imageRepo[_]
        startswith(image, repo)
        
