apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8snodeportcheck
spec:
  crd:
    spec:
      names:
        kind: K8sNodeportCheck
      validation:
        openAPIV3Schema:
          type: object
          properties:
            minNodePort:
              type: integer
        
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8snodeportcheck
        violation[{"msg": msg}] {
          input.review.object.spec.type == "NodePort"
          port := input.review.object.spec.ports[_]
          port.nodePort <= input.parameters.minNodePort
          msg := sprintf(
            "Service '%s' uses NodePort %v. NodePort must be greater than %v",
            [
              input.review.object.metadata.name,
              port.nodePort,
              input.parameters.minNodePort
            ]
          ) 
        }